[package]
name = "jerry"
version = "0.1.0"
edition = "2018"
description = "Shallow multithreaded web server"
license = "MIT"

[[bin]]
name = "jerry"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
clap = "3.1.6"
env_logger = "0.9.0"
log = "0.4.0"
